name: Blacklist Monitor

on:
  schedule:
    - cron: '0 0 * * *'  # This will run the workflow daily at midnight.
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - run: git config --global user.email "fabrizio.salmi@gmail.com"
    - run: git config --global user.name "fabriziosalmi"
    - name: Check out repository code
      uses: actions/checkout@v4
      with:
        fetch-depth: 1  # Shallow clones should be disabled to decrease time waste 
        ref: main
        token: ${{ secrets.PAT }}

    - name: Check and Update Blacklists
      run: |
        python .github/scripts/check_blacklists.py
    - name: Refresh repository
      run: git pull https://fabriziosalmi:${{ secrets.PAT }}@github.com/fabriziosalmi/blacklists
    - name: Add updated blacklists_monitor.md to repository
      run: git add blacklists_monitor.md && git commit -m "blacklist monitor update" 
    - name: Push to repository
      run: git push https://fabriziosalmi:${{ secrets.PAT }}@github.com/fabriziosalmi/blacklists
