name: Blacklist Monitor

on:
  schedule:
    - cron: '0 0 * * *'  # This will run the workflow daily at midnight.
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - name: Setup Git Configurations
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "github-actions[bot]"

    - name: Check out repository code
      uses: actions/checkout@v2
      with:
        fetch-depth: 1
        ref: main
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Install dependencies
      run: |
        pip install tqdm requests

    - name: Check and Update Blacklists
      run: |
        python .github/scripts/check_blacklists.py

    - name: Add updated blacklists_monitor.md to repository
      run: |
        git add blacklists_monitor.md
        git commit -m "blacklist monitor update" 
        git push
