name: Check Recent Blacklist Changes

on:
  workflow_dispatch:

jobs:
  check-blacklists:
    runs-on: ubuntu-latest

    steps:
    - name: Setup Git Configurations
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "github-actions[bot]"

    - name: Check out repository code
      uses: actions/checkout@v4
      with:
        fetch-depth: 1  # Fetch all history for completeness
        ref: main
        token: ${{ secrets.PAT }}

    - name: Fetch recent blacklist changes
      run: |
        # Make an API call to fetch the data with the specified headers
        curl https://changedetection.domainsblacklists.com/api/v1/watch -H "user-agent:{{ secrets.DB_UA}}" -H "x-api-key:{{ secrets.CD_API_KEY}}" > data.json        
        current_timestamp=$(date +%s)
        one_day_ago=$(($current_timestamp - 86400))
        cat data.json | jq --argjson oda "$one_day_ago" 'to_entries[] | select(.value.last_changed > $oda) | .value.url' > most-updates.blacklists.urls
        
    - name: Commit and push if there are changes
      run: |
        git config user.name "GitHub Action"
        git config user.email "action@github.com"
        
        git add most-updates.blacklists.urls
        git commit -m "Update most-updates.blacklists.urls with recent changes" || echo "No changes to commit"
        git pull --rebase origin main
        git push origin main
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}
