name: Compare Blacklist Changes

on:
  push:
    paths:
      - 'all.fqdn.blacklist.tar.gz'
  workflow_dispatch:

jobs:
  compare:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository code
      uses: actions/checkout@v2
      with:
        fetch-depth: 50

    - name: Get commit hashes for the latest changes of the file
      id: get_commits
      run: |
        commits=$(git log --pretty=format:"%H" -n 50 -- all.fqdn.blacklist.tar.gz | head -n 2)
        echo "::set-output name=latest_commit::$(echo "$commits" | head -n 1)"
        echo "::set-output name=previous_commit::$(echo "$commits" | tail -n 1)"

    - name: Extract current and previous version of the blacklist
      run: |
        git checkout ${{ steps.get_commits.outputs.latest_commit }}
        mkdir current && tar -xzf all.fqdn.blacklist.tar.gz -C current
        mv current/all.fqdn.blacklist current_blacklist.txt

        git checkout ${{ steps.get_commits.outputs.previous_commit }}
        mkdir previous && tar -xzf all.fqdn.blacklist.tar.gz -C previous
        mv previous/all.fqdn.blacklist previous_blacklist.txt

    - name: Compare and output changes
      run: |
        echo "Added domains:" > changes.txt
        comm -13 previous_blacklist.txt current_blacklist.txt >> changes.txt
        echo "" >> changes.txt
        echo "Removed domains:" >> changes.txt
        comm -23 previous_blacklist.txt current_blacklist.txt >> changes.txt
        
        cat changes.txt
