name: GitHub release

on:
  push:
    branches:
      - main
    paths:
      - 'all.fqdn.blacklist.tar.gz'

  workflow_dispatch:

jobs:
  Create-release:
    runs-on: ubuntu-latest  # Change this back to self-hosted once you confirm it works

    steps:
    - name: Check out repository code
      uses: actions/checkout@v2  # Change this to a version you know is stable
      with:
        fetch-depth: 1
        ref: main

    - name: Delete old 'latest' tag (locally and remotely)
      run: |
        git tag -d latest || echo "Local tag not found, proceeding..."
        git push --delete origin latest || echo "Remote tag not found, proceeding..."
        
    - name: Create new 'latest' tag
      run: |
        git tag -fa latest -m "Latest release"
        git push origin main --tags --force  # Force is needed to overwrite the existing 'latest' tag
        
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      with:
        tag_name: latest
        release_name: "Domains blacklist"
        body: Auto-generated release from GitHub Actions.
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload Release Asset
      id: upload-release-asset
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./all.fqdn.blacklist.tar.gz
        asset_name: latest.tar.gz
        asset_content_type: application/gzip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
