name: GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - 'all.fqdn.blacklist.tar.gz'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  Deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          ref: main
          token: ${{ secrets.PAT }}

      - name: Extract and Rename
        run: |
          mkdir extracted
          tar -xzf all.fqdn.blacklist.tar.gz -C extracted
          mv extracted/all.fqdn.blacklist extracted/blacklist.txt

      # Create the fancy index.html.
      - name: Create fancy index.html
        run: |
          echo '<!DOCTYPE html><html><head><title>Blacklist</title></head><body><h1>Welcome to the Blacklist</h1><a href="blacklist.txt">Download the Blacklist</a></body></html>' > extracted/index.html

      # Now, move to GitHub Pages deployment
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.PAT }}
          publish_dir: ./extracted
