name: GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - 'all.fqdn.blacklist.tar.gz'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  Deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: self-hosted

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          ref: main
          token: ${{ secrets.PAT }}

      - name: Extract and Rename
        run: |
          mkdir extracted
          tar -xzf all.fqdn.blacklist.tar.gz -C extracted
          mv extracted/all.fqdn.blacklist extracted/blacklist.txt

      # Assuming you want a fancy index.html. You can create this yourself.
      - name: Create fancy index.html
        run: |
          echo '<!DOCTYPE html><html><head><title>Blacklist</title></head><body><h1>Welcome to the Blacklist</h1><a href="blacklist.txt">Download the Blacklist</a></body></html>' > extracted/index.html

      # Now, move to GitHub Pages deployment
      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
        with:
          branch: gh-pages  # default is gh-pages
          target_folder: extracted  # Deploy the content from 'extracted' directory
