name: Generate and Release blacklist.txt

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  Generate-Blacklist:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Git Configurations
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "github-actions[bot]"

    - name: Check out repository code
      uses: actions/checkout@v4
      with:
        fetch-depth: 1  # Fetch all history for completeness
        ref: main
        token: ${{ secrets.PAT }}

    - name: Generate blacklist
      run: sudo /bin/bash generate_fqdn.sh

    - name: Commit and Push updated blacklist to repository
      run: |
        git add all.fqdn.blacklist.tar.gz 
        git commit -m "Updated blacklist."
        git pull --rebase origin main
        git push origin main
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}
        
  Create-Release:
    needs: Generate-Blacklist
    runs-on: ubuntu-latest
    steps:
    - name: Setup Git Configurations
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "github-actions[bot]"

    - name: Check out repository code
      uses: actions/checkout@v4
      with:
        fetch-depth: 1  # Fetch all history for completeness
        ref: main
        token: ${{ secrets.PAT }}

    # Extract current blacklist
    # Extract current blacklist
    - name: Extract current blacklist.txt
      run: |
        mkdir current
        tar -xzf all.fqdn.blacklist.tar.gz -C current
        mv current/all.fqdn.blacklist current/blacklist.txt

    - name: Count domains in blacklist
      id: count_domains
      run: |
        count=$(wc -l < current/blacklist.txt)
        echo "Number of domains: $count"
        echo "::set-output name=count::$count"

    - name: Delete Release if Exists
      run: |
        release_id=$(curl -H "Authorization: token ${{ secrets.PAT }}" -s "https://api.github.com/repos/$GITHUB_REPOSITORY/releases/tags/latest" | jq .id)
        if [ "$release_id" != "null" ]; then
          curl -X DELETE -H "Authorization: token ${{ secrets.PAT }}" "https://api.github.com/repos/$GITHUB_REPOSITORY/releases/$release_id"
        fi

    - name: Delete Tag if Exists
      run: |
        if git show-ref --tags latest; then
          git push --delete origin latest
        fi

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      with:
        tag_name: latest
        release_name: "Domains Blacklist"
        body: "Domains: ${{ steps.count_domains.outputs.count }}"
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}

    - name: Upload Release Asset (Blacklist)
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./current/blacklist.txt
        asset_name: blacklist.txt
        asset_content_type: text/plain
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}

    - name: Clean up
      run: rm -r current

  Generate-RPZ:
    needs: Create-Release
    runs-on: ubuntu-latest
    steps:
    - name: Setup Git Configurations
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "github-actions[bot]"

    - name: Check out repository code
      uses: actions/checkout@v4
      with:
        fetch-depth: 1
        ref: main
        token: ${{ secrets.PAT }}

    - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt install -y bind9utils

    - name: Extract and Convert
      run: |
        mkdir output
        tar -xzf all.fqdn.blacklist.tar.gz
        cat all.fqdn.blacklist | while read line; do echo "$line CNAME ."; done > output/rpz_blacklist.txt
        tar -czf rpz_blacklist.tar.gz -C output rpz_blacklist.txt
    
    - name: Commit and Push updated blacklist to repository
      run: |
        git add rpz_blacklist.tar.gz 
        git commit -m "RPZ updated"
        git pull --rebase origin main
        git push origin main
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}
