name: Blacklist Stats

on:
  schedule:
    - cron: '10 * * * *'  # Run every hour
    
jobs:
  generate_stats:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 2  # Fetch the last 2 commits instead of just the latest

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run blacklist stats script
        run: |
          python3 stats_new.py > stats.md

      - name: Commit and push stats.md
        uses: EndBug/add-and-commit@v9
        with:
          author_name: "GitHub Actions"
          author_email: "actions@github.com"
          message: "Update stats.md"
          add: "stats.md"
