name: Stats

on:
  workflow_dispatch:
  schedule:
    - cron: '10 * * * *'  # This will run the action every hour. Adjust as needed.

jobs:
  fetch-stats:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository code
      uses: actions/checkout@v2

    - name: Fetch and calculate stats
      run: |
        BLACKLISTED_COUNT=$(curl -sL "https://github.com/fabriziosalmi/blacklists/releases/download/latest/blacklist.txt" | wc -l)
        WHITELISTED_COUNT=$(curl -sL "https://raw.githubusercontent.com/fabriziosalmi/blacklists/main/whitelist.txt" | wc -l)
        BLACKLISTS_SOURCE_COUNT=$(curl -sL "https://raw.githubusercontent.com/fabriziosalmi/blacklists/main/blacklists.fqdn.urls" | wc -l)
        STREAMING_BLACKLIST_COUNT=$(curl -sL "https://raw.githubusercontent.com/fabriziosalmi/blacklists/main/custom/streaming.txt" | wc -l)

        echo "| Metric | Count |" > stats.md
        echo "|--------|------:|" >> stats.md
        echo "| Total Blacklisted Domains | $BLACKLISTED_COUNT |" >> stats.md
        echo "| Total Whitelisted Domains | $WHITELISTED_COUNT |" >> stats.md
        echo "| Total Blacklist Sources | $BLACKLISTS_SOURCE_COUNT |" >> stats.md
        echo "| Total Custom Blacklisted Domains | $STREAMING_BLACKLIST_COUNT |" >> stats.md
        echo "---" >> stats.md
        echo "### Badges" >> stats.md
        echo "- ![Static Badge](https://img.shields.io/badge/blacklisted-$BLACKLISTED_COUNT-cc0000)" >> stats.md
        echo "- ![Static Badge](https://img.shields.io/badge/whitelisted-$WHITELISTED_COUNT-00CC00)" >> stats.md
        echo "- ![Static Badge](https://img.shields.io/badge/blacklists-$BLACKLISTS_SOURCE_COUNT-000000)" >> stats.md
        echo "- ![Static Badge](https://img.shields.io/badge/custom_blacklisted-$STREAMING_BLACKLIST_COUNT-000000)" >> stats.md

    - name: Commit and push stats.md
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add stats.md
        git commit -m "Stats updated."
        git pull --rebase origin main
        git push origin main
