name: Validate and Sort whitelist.txt

on:
  push:
    paths:
      - 'whitelist.txt'

jobs:
  process:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Process and validate whitelist.txt
      run: |
        # Lowercase, sort and uniq
        sort -uf whitelist.txt | tr 'A-Z' 'a-z' > sorted.txt
        mv sorted.txt whitelist.txt

        # Validate FQDNs
        while IFS= read -r fqdn; do
            if ! echo "$fqdn" | grep -Pq "^((?!-)[A-Za-z0-9-]{1,63}(?<!-)\.)+[A-Za-z]{2,6}$"; then
                echo "Invalid FQDN: $fqdn"
                exit 1
            fi
        done < whitelist.txt

    - name: Commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add whitelist.txt
        git commit -m "Sort and validate whitelist.txt" || echo "No changes to commit"
        git push
