name: Whitelist

on:
  push:
    branches:
      - main
    paths:
      - 'whitelist.txt'

jobs:
  update-whitelist:
    runs-on: ubuntu-latest

    steps:
    - name: Set git user
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"

    - name: Check out repository code
      uses: actions/checkout@v4
      with:
        fetch-depth: 2  
        
    - name: Sort and remove duplicates from whitelist.txt
      run: |
        sort -u whitelist.txt -o whitelist.txt

    - name: Commit and push if there are changes
      run: |
        LINES=$(wc -l < whitelist.txt)
        git add whitelist.txt
        git diff-index --quiet HEAD || git commit -m "Updated whitelist.txt - Total FQDNs: $LINES"
        git push
