name: Whitelist

on:
  push:
    branches:
      - main
    paths:
      - 'whitelist.txt'
  workflow_dispatch:

jobs:
  update-whitelist:
    runs-on: ubuntu-latest

    steps:
    - name: Set git user
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"

    - name: Check out repository code
      uses: actions/checkout@v2  # Use v2 which is a newer version than v3
      with:
        fetch-depth: 0  # Fetch all history so git can detect changes properly

    - name: Sort and remove duplicates from whitelist.txt
      run: |
        sort -u whitelist.txt -o whitelist.txt

    - name: Commit and push if there are changes
      run: |
        git diff
        git add whitelist.txt
        git diff-index --quiet HEAD || git commit -m "Update whitelist.txt"
        git push
